# --> Catppuccin (Mocha)
set -ogq @thm_bg "#1e1e2e"
set -ogq @thm_fg "#cdd6f4"
set -gF status-fg "#{@thm_fg}"
set -gF status-bg "#{@thm_bg}"

set -g @thm_rosewater "#f5e0dc"
set -g @thm_flamingo "#f2cdcd"
set -g @thm_pink "#f5c2e7"
set -g @thm_mauve "#cba6f7"
set -g @thm_red "#f38ba8"
set -g @thm_maroon "#eba0ac"
set -g @thm_peach "#fab387"
set -g @thm_yellow "#f9e2af"
set -g @thm_green "#a6e3a1"
set -g @thm_teal "#94e2d5"
set -g @thm_sky "#89dceb"
set -g @thm_sapphire "#74c7ec"
set -g @thm_blue "#89b4fa"
set -g @thm_lavender "#b4befe"

set -g @thm_subtext_1 "#a6adc8"
set -g @thm_subtext_0 "#bac2de"
set -g @thm_overlay_2 "#9399b2"
set -g @thm_overlay_1 "#7f849c"
set -g @thm_overlay_0 "#6c7086"
set -g @thm_surface_2 "#585b70"
set -g @thm_surface_1 "#45475a"
set -g @thm_surface_0 "#313244"
set -g @thm_mantle "#181825"
set -g @thm_crust "#11111b"

#[bg=default]#[fg=#{@thm_flamingo}]#[bg=#{@thm_flamingo}]#[fg=#{@thm_bg}]
#[bg=default]#[fg=#{@thm_teal}]#[bg=#{@thm_teal}]#[fg=#{@thm_bg}]

set -g status-left ''
set -g status-right ''
set -g status-left '#{?client_prefix,#[bg=#{@thm_flamingo}]#[fg=#{@thm_crust}] ♥ #[bg=default]#[fg=#{@thm_flamingo}]#[bg=#{@thm_flamingo}]#[fg=#{@thm_bg}],#[bg=#{@thm_teal}]#[fg=#{@thm_crust}] ♠ #[bg=default]#[fg=#{@thm_teal}]#[bg=#{@thm_teal}]#[fg=default]}'
#set -g status-right '#[align=absolute-centre]#[fg=#{@thm_mauve},bg=default]#[bg=#{@thm_mauve},fg=#{@thm_crust}] #W #[fg=#{@thm_mauve},bg=default]#[align=right]'
#set -ag status-right '#{E:@catppuccin_status_host}#{E:@catppuccin_status_date_time}'
set -g window-status-separator ''
set -ag status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] #H #[bg=#{@thm_flamingo}] #S #[bg=#{@thm_blue}] %H:%M '

setw -g window-status-current-style 'fg=#{@thm_fg} bg=#{@thm_bg}'
setw -g window-status-current-format '#[bg=default]#[fg=#{@thm_blue}]#[bg=#{@thm_blue}]#[fg=#{@thm_bg}]'
setw -ag window-status-current-format '#[bg=#{@thm_blue},fg=#{@thm_crust}] #I #[fg=#{@thm_flamingo}]#[fg=#{@thm_crust},bg=#{@thm_flamingo}] #W #[bg=#{@thm_flamingo},fg=#{@thm_surface_0}]#F'
setw -ag window-status-current-format '#[bg=default]#[fg=#{@thm_flamingo}]#[bg=#{@thm_flamingo}]#[fg=#{@thm_bg}]'

setw -g window-status-style 'fg=#{@thm_fg} bg=#{@thm_bg}'
setw -g window-status-format '#[bg=#{@thm_surface_0},fg=#{@thm_bg}]#[fg=#{@thm_blue}] #I #[fg=#{@thm_flamingo}]#W #F #[bg=#{@thm_bg},fg=#{@thm_surface_0}]'

setw -g window-status-bell-style 'fg=yellow bg=red bold'

set -g status-right-length 100

set -g prefix C-x

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set-option -g allow-rename off

bind h select-pane -L 
bind j select-pane -D 
bind k select-pane -U 
bind l select-pane -R
