#set -g @catppuccin_reset true

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_status_style "custom"
set -g @catppuccin_status_background "default"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "yes"

set -g @catppuccin_window_current_text "#[bg=default]"
set -g @catppuccin_window_current_number " #[bold]#I "
set -g @catppuccin_window_number "#[bg=#{@thm_rosewater},fg=#{@thm_crust}] #I "
set -g @catppuccin_window_text "#[bg=#{@thm_surface_0},fg=#{@thm_mauve},bold] #W "
# Look at the bullcrap I have to do to make this work
# :anger:
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_middle_separator "#[fg=#{@thm_rosewater},bg=#{@thm_surface_0}]#[bg=#{@thm_rosewater},fg=#{@thm_surface_0}]"
set -g @catppuccin_window_left_separator "#[bg=default,fg=#{@thm_rosewater}]#[fg=default,bg=#{@thm_rosewater}]"
set -g @catppuccin_window_right_separator "#[fg=#{@thm_surface_0},bg=default]#[bg=#{@thm_surface_0},fg=default]"
set -g @catppuccin_window_current_left_separator "#[bg=default,fg=#{@thm_blue}]#[bg=#{@thm_blue},fg=#{@thm_bg}]"
set -g @catppuccin_window_current_middle_separator ""
set -g @catppuccin_window_current_right_separator "#[bg=default,fg=#{@thm_blue}]#[bg=#{@thm_blue},fg=#{@thm_bg}]"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

#[bg=default]#[fg=#{@thm_flamingo}]#[bg=#{@thm_flamingo}]#[fg=#{@thm_bg}]
#[bg=default]#[fg=#{@thm_teal}]#[bg=#{@thm_teal}]#[fg=#{@thm_bg}]

set -g status-left '#[fg=#{@thm_crust}]#{?client_prefix,#[bg=#{@thm_flamingo}] ♥ #[bg=default]#[fg=#{@thm_flamingo}]#[bg=#{@thm_flamingo}]#[fg=#{@thm_bg}]
,#[bg=#{@thm_teal}] ♠ #[bg=default]#[fg=#{@thm_teal}]#[bg=#{@thm_teal}]#[fg=#{@thm_bg}]}#[bg=default]'
set -g status-right '#[align=absolute-centre]#[fg=#{@thm_mauve},bg=default]#[bg=#{@thm_mauve},fg=#{@thm_crust}] #W #[fg=#{@thm_mauve},bg=default]#[align=right]'
set -ag status-right '#{E:@catppuccin_status_host}#{E:@catppuccin_status_date_time}'
set -g window-status-separator ''
#set -ag status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] #H #[bg=#{@thm_flamingo}] #S #[bg=#{@thm_blue}] %H:%M '

set -g status-right-length 100

set -g prefix C-x

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind h select-pane -L 
bind j select-pane -D 
bind k select-pane -U 
bind l select-pane -R
